INFO 2025-10-15 21:00:48,402 autoreload 75968 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:00:53,141 autoreload 76129 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:06:14,142 autoreload 76406 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:06:47,159 autoreload 76638 8765440320 Watching for file changes with StatReloader
WARNING 2025-10-15 21:06:52,498 log 76638 6160855040 Not Found: /
WARNING 2025-10-15 21:06:52,620 log 76638 6160855040 Not Found: /favicon.ico
WARNING 2025-10-15 21:11:33,412 log 76638 6160281600 Not Found: /
ERROR 2025-10-15 21:11:42,205 log 76638 6177107968 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `version` is not valid for model `AIModule`.
ERROR 2025-10-15 21:11:42,268 log 76638 6177107968 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `version` is not valid for model `AIModule`.
WARNING 2025-10-15 21:11:47,677 log 76638 6160281600 Not Found: /api/shema/
ERROR 2025-10-15 21:11:56,193 log 76638 6160281600 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `version` is not valid for model `AIModule`.
ERROR 2025-10-15 21:12:05,814 log 76638 6177107968 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `version` is not valid for model `AIModule`.
ERROR 2025-10-15 21:12:05,874 log 76638 6177107968 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `version` is not valid for model `AIModule`.
WARNING 2025-10-15 21:12:36,905 log 76638 6193934336 Not Found: /
INFO 2025-10-15 21:13:31,550 autoreload 76638 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:13:32,239 autoreload 77002 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:13:33,631 autoreload 77002 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:13:34,074 autoreload 77015 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:13:49,822 autoreload 77015 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:13:50,379 autoreload 77020 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:13:59,962 autoreload 77020 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:14:00,531 autoreload 77031 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:16:28,504 autoreload 77031 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:16:29,174 autoreload 77134 8765440320 Watching for file changes with StatReloader
WARNING 2025-10-15 21:16:52,481 log 77134 6125088768 Not Found: /info/
WARNING 2025-10-15 21:17:11,190 log 77134 6125088768 Forbidden: /health/info/
WARNING 2025-10-15 21:18:45,498 log 77134 6125088768 Not Found: /info/
WARNING 2025-10-15 21:18:48,846 log 77134 6125088768 Not Found: /
INFO 2025-10-15 21:19:50,915 autoreload 77134 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:19:51,624 autoreload 77283 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:20:00,196 autoreload 77283 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:20:00,847 autoreload 77303 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:20:20,742 autoreload 77303 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-15 21:20:21,346 autoreload 77316 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:25:06,594 autoreload 77316 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:25:07,398 autoreload 77518 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:25:13,945 autoreload 77518 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:25:14,491 autoreload 77531 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:25:18,915 autoreload 77531 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:25:19,312 autoreload 77537 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:25:38,964 autoreload 77834 8765440320 Watching for file changes with StatReloader
WARNING 2025-10-15 21:25:46,204 log 77834 6202716160 Not Found: /
ERROR 2025-10-15 21:25:56,893 log 77834 6202716160 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `license_type` is not valid for model `AIModule`.
ERROR 2025-10-15 21:25:56,952 log 77834 6202716160 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `license_type` is not valid for model `AIModule`.
INFO 2025-10-15 21:26:40,616 autoreload 77834 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:26:41,275 autoreload 77889 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:26:43,634 autoreload 77889 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:26:44,048 autoreload 77895 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:26:45,337 autoreload 77895 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:26:51,247 autoreload 78174 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-15 21:26:53,046 log 78174 6124679168 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `published_at` is not valid for model `AIModule`.
ERROR 2025-10-15 21:26:53,113 log 78174 6124679168 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 111, in get_operation
    operation['responses'] = self._get_response_bodies()
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1367, in _get_response_bodies
    return {'200': self._get_response_for_code(response_serializers, '200', direction=direction)}
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1423, in _get_response_for_code
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `published_at` is not valid for model `AIModule`.
INFO 2025-10-15 21:27:18,497 autoreload 78174 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:27:19,133 autoreload 78208 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:27:24,595 autoreload 78208 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:27:25,059 autoreload 78217 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:27:26,309 autoreload 78217 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:27:26,674 autoreload 78218 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:27:35,243 autoreload 78496 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-15 21:27:37,399 log 78496 6162919424 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1026, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 672, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `installation_guide` is not valid for model `AIModuleDetail`.
ERROR 2025-10-15 21:27:37,454 log 78496 6162919424 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1026, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 672, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `installation_guide` is not valid for model `AIModuleDetail`.
INFO 2025-10-15 21:28:32,752 autoreload 78496 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:28:33,407 autoreload 78530 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:28:34,748 autoreload 78530 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:28:35,170 autoreload 78535 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:29:01,054 autoreload 78824 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-15 21:29:16,585 log 78824 6126055424 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1026, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 672, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `usage_examples` is not valid for model `AIModuleDetail`.
ERROR 2025-10-15 21:29:16,638 log 78824 6126055424 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1026, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 672, in _map_serializer_field
    component = self.resolve_serializer(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `usage_examples` is not valid for model `AIModuleDetail`.
INFO 2025-10-15 21:29:47,041 autoreload 78824 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/api/serializers.py changed, reloading.
INFO 2025-10-15 21:29:47,623 autoreload 78848 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:29:49,974 autoreload 78848 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/api/serializers.py changed, reloading.
INFO 2025-10-15 21:29:50,348 autoreload 78857 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:30:03,035 autoreload 78857 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/api/serializers.py changed, reloading.
INFO 2025-10-15 21:30:03,443 autoreload 78873 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:30:04,723 autoreload 78873 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/api/serializers.py changed, reloading.
INFO 2025-10-15 21:30:05,123 autoreload 78877 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:30:06,283 autoreload 78877 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/api/serializers.py changed, reloading.
INFO 2025-10-15 21:30:06,658 autoreload 78881 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:30:12,069 autoreload 78881 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-15 21:30:12,458 autoreload 78893 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:30:27,870 autoreload 79260 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-15 21:30:30,169 log 79260 6166376448 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1026, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 667, in _map_serializer_field
    schema = self._unwrap_list_serializer(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1399, in _unwrap_list_serializer
    result = self._unwrap_list_serializer(serializer.child, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1396, in _unwrap_list_serializer
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `impact_factor` is not valid for model `Publication`.
ERROR 2025-10-15 21:30:30,237 log 79260 6166376448 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 84, in get
    return self._get_schema_response(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 281, in get_schema
    paths=self.parse(request, public),
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/generators.py", line 252, in parse
    operation = view.schema.get_operation(
        path, path_regex, path_prefix, method, self.registry
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 99, in get_operation
    request_body = self._get_request_body()
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1295, in _get_request_body
    schema, partial_request_body_required = self._get_request_for_media_type(serializer, direction)
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1327, in _get_request_for_media_type
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1026, in _map_basic_serializer
    schema = self._map_serializer_field(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 667, in _map_serializer_field
    schema = self._unwrap_list_serializer(field, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1399, in _unwrap_list_serializer
    result = self._unwrap_list_serializer(serializer.child, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1396, in _unwrap_list_serializer
    component = self.resolve_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1605, in resolve_serializer
    component.schema = self._map_serializer(serializer, direction, bypass_extensions)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 927, in _map_serializer
    schema = self._map_basic_serializer(serializer, direction)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/drf_spectacular/openapi.py", line 1020, in _map_basic_serializer
    for field in serializer.fields.values():
                 ^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ~~~~~~~~~~~~~~~~^
        source, info, model, depth
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
    ...<2 lines>...
    )
django.core.exceptions.ImproperlyConfigured: Field name `impact_factor` is not valid for model `Publication`.
INFO 2025-10-15 21:30:47,917 autoreload 79260 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/api/serializers.py changed, reloading.
INFO 2025-10-15 21:30:48,546 autoreload 79293 8765440320 Watching for file changes with StatReloader
INFO 2025-10-15 21:30:54,625 autoreload 79410 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:21:33,010 autoreload 1359 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:21:43,434 autoreload 1359 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/publications/admin.py changed, reloading.
INFO 2025-10-16 12:21:43,905 autoreload 1369 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:22:14,684 autoreload 1369 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/publications/admin.py changed, reloading.
INFO 2025-10-16 12:22:15,235 autoreload 1400 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:24:08,490 autoreload 1400 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/admin.py changed, reloading.
INFO 2025-10-16 12:24:09,162 autoreload 1497 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:24:24,952 autoreload 1497 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/admin.py changed, reloading.
INFO 2025-10-16 12:24:25,511 autoreload 1519 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:24:30,937 autoreload 1519 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/admin.py changed, reloading.
INFO 2025-10-16 12:24:31,323 autoreload 1531 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:25:01,566 autoreload 1531 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/tags/admin.py changed, reloading.
INFO 2025-10-16 12:25:02,160 autoreload 1557 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:25:09,679 autoreload 1557 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/publications/admin.py changed, reloading.
INFO 2025-10-16 12:25:10,330 autoreload 1573 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:25:24,001 autoreload 1573 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/common/admin.py changed, reloading.
INFO 2025-10-16 12:25:24,393 autoreload 1590 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-16 12:33:28,984 log 1590 6171619328 Internal Server Error: /admin/ai_modules/aimodule/add/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/forms/forms.py", line 178, in __getitem__
    field = self.fields[name]
            ~~~~~~~~~~~^^^^^^
KeyError: 'slug'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1828, in _changeform_view
    admin_form = helpers.AdminForm(
        form,
    ...<6 lines>...
        model_admin=self,
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/helpers.py", line 53, in __init__
    {"field": form[field_name], "dependencies": [form[f] for f in dependencies]}
              ~~~~^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/forms/forms.py", line 180, in __getitem__
    raise KeyError(
    ...<6 lines>...
    )
KeyError: "Key 'slug' not found in 'AIModuleForm'. Choices are: company, country, created_by, meta_description, name, params_count, search_vector, status, task_short_description."
ERROR 2025-10-16 12:33:47,700 log 1590 6137966592 Internal Server Error: /admin/ai_modules/aimodule/add/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/forms/forms.py", line 178, in __getitem__
    field = self.fields[name]
            ~~~~~~~~~~~^^^^^^
KeyError: 'slug'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1828, in _changeform_view
    admin_form = helpers.AdminForm(
        form,
    ...<6 lines>...
        model_admin=self,
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/helpers.py", line 53, in __init__
    {"field": form[field_name], "dependencies": [form[f] for f in dependencies]}
              ~~~~^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/forms/forms.py", line 180, in __getitem__
    raise KeyError(
    ...<6 lines>...
    )
KeyError: "Key 'slug' not found in 'AIModuleForm'. Choices are: company, country, created_by, meta_description, name, params_count, search_vector, status, task_short_description."
INFO 2025-10-16 12:36:32,883 autoreload 1590 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/admin.py changed, reloading.
INFO 2025-10-16 12:36:33,574 autoreload 2224 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:36:41,081 autoreload 2224 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/admin.py changed, reloading.
INFO 2025-10-16 12:36:41,622 autoreload 2242 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:36:44,919 autoreload 2242 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/admin.py changed, reloading.
INFO 2025-10-16 12:36:45,290 autoreload 2253 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-16 12:38:18,039 log 2253 6122336256 Internal Server Error: /admin/ai_modules/aimodule/1/change/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/forms/forms.py", line 178, in __getitem__
    field = self.fields[name]
            ~~~~~~~~~~~^^^^^^
KeyError: 'slug'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1828, in _changeform_view
    admin_form = helpers.AdminForm(
        form,
    ...<6 lines>...
        model_admin=self,
    )
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/contrib/admin/helpers.py", line 53, in __init__
    {"field": form[field_name], "dependencies": [form[f] for f in dependencies]}
              ~~~~^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/forms/forms.py", line 180, in __getitem__
    raise KeyError(
    ...<6 lines>...
    )
KeyError: "Key 'slug' not found in 'AIModuleForm'. Choices are: company, country, created_by, meta_description, name, params_count, search_vector, status, task_short_description."
INFO 2025-10-16 12:39:50,791 autoreload 2253 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/admin.py changed, reloading.
INFO 2025-10-16 12:39:51,491 autoreload 2419 8765440320 Watching for file changes with StatReloader
WARNING 2025-10-16 12:44:24,301 log 2419 6195163136 Not Found: /docs/
ERROR 2025-10-16 12:44:50,713 log 2419 6195163136 Internal Server Error: /api/v1/ai-modules/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/throttling.py", line 92, in get_rate
    return self.THROTTLE_RATES[self.scope]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'burst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 416, in initial
    self.check_throttles(request)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 358, in check_throttles
    for throttle in self.get_throttles():
                    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 284, in get_throttles
    return [throttle() for throttle in self.throttle_classes]
            ~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/throttling.py", line 70, in __init__
    self.rate = self.get_rate()
                ~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/throttling.py", line 95, in get_rate
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No default throttle rate set for 'burst' scope
WARNING 2025-10-16 12:45:17,726 log 2419 6195163136 Bad Request: /api/auth/register/
WARNING 2025-10-16 12:47:08,074 log 2419 6195163136 Not Found: /
/api/auth/register/
ERROR 2025-10-16 12:47:34,248 utils 2419 6195163136 Failed to send email to firesieht@mail.ru: emails/welcome.html
ERROR 2025-10-16 12:47:58,098 log 2419 6195163136 Internal Server Error: /api/v1/ai-modules/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/throttling.py", line 92, in get_rate
    return self.THROTTLE_RATES[self.scope]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'burst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 416, in initial
    self.check_throttles(request)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 358, in check_throttles
    for throttle in self.get_throttles():
                    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 284, in get_throttles
    return [throttle() for throttle in self.throttle_classes]
            ~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/throttling.py", line 70, in __init__
    self.rate = self.get_rate()
                ~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/throttling.py", line 95, in get_rate
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No default throttle rate set for 'burst' scope
INFO 2025-10-16 12:49:39,828 autoreload 2419 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/config/settings/base.py changed, reloading.
INFO 2025-10-16 12:49:40,430 autoreload 3020 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:49:41,749 autoreload 3020 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/config/settings/base.py changed, reloading.
INFO 2025-10-16 12:49:42,126 autoreload 3027 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-16 12:49:47,429 log 3027 6204764160 Internal Server Error: /api/v1/ai-modules/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/apps/api/viewsets.py", line 84, in get_queryset
    if not (self.request.user.is_authenticated and self.request.user.is_admin()):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'is_admin'
ERROR 2025-10-16 12:50:45,206 log 3027 6204764160 Internal Server Error: /api/v1/ai-modules/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ~~~~~~~~~~~~~~~~~^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/apps/api/viewsets.py", line 84, in get_queryset
    if not (self.request.user.is_authenticated and self.request.user.is_admin()):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'is_admin'
INFO 2025-10-16 12:52:13,432 autoreload 3027 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 12:52:13,938 autoreload 3165 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:52:19,270 autoreload 3165 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 12:52:19,526 autoreload 3178 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:52:20,750 autoreload 3178 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 12:52:21,191 autoreload 3185 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:54:31,338 autoreload 3185 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 12:54:31,814 autoreload 3264 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:54:34,079 autoreload 3264 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 12:54:34,490 autoreload 3280 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:54:59,556 autoreload 3280 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 12:54:59,996 autoreload 3308 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 12:55:03,268 autoreload 3308 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 12:55:03,630 autoreload 3316 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:07,022 autoreload 3316 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/common/models.py changed, reloading.
INFO 2025-10-16 13:00:07,507 autoreload 3468 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:08,762 autoreload 3468 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/common/models.py changed, reloading.
INFO 2025-10-16 13:00:09,021 autoreload 3478 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:10,242 autoreload 3478 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/common/models.py changed, reloading.
INFO 2025-10-16 13:00:10,515 autoreload 3479 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:18,817 autoreload 3479 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/common/models.py changed, reloading.
INFO 2025-10-16 13:00:19,210 autoreload 3487 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:28,903 autoreload 3487 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 13:00:29,463 autoreload 3503 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:31,808 autoreload 3503 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 13:00:32,108 autoreload 3511 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:33,333 autoreload 3511 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 13:00:33,667 autoreload 3512 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:38,040 autoreload 3512 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/accounts/models.py changed, reloading.
INFO 2025-10-16 13:00:38,449 autoreload 3525 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:56,391 autoreload 3525 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:00:56,780 autoreload 3545 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:00:58,027 autoreload 3545 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:00:58,424 autoreload 3554 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:01:09,060 autoreload 3554 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:01:09,606 autoreload 3573 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:01:25,519 autoreload 3573 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:01:25,839 autoreload 3588 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:01:32,138 autoreload 3588 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:01:32,502 autoreload 3597 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:01:33,803 autoreload 3597 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:01:34,181 autoreload 3600 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-16 13:03:26,722 log 3600 6198439936 Internal Server Error: /api/v1/ai-modules/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/Users/firesieht/Documents/programming/BRICS/backend/apps/api/serializers.py", line 226, in get_is_liked
    return obj.is_liked_by(request.user)
           ^^^^^^^^^^^^^^^
AttributeError: 'AIModule' object has no attribute 'is_liked_by'
INFO 2025-10-16 13:05:24,310 autoreload 3600 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:05:24,860 autoreload 3755 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:05:27,159 autoreload 3755 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/ai_modules/models.py changed, reloading.
INFO 2025-10-16 13:05:27,573 autoreload 3771 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-16 13:06:04,507 log 3771 6185594880 Internal Server Error: /api/v1/ai-modules/export/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/apps/api/viewsets.py", line 269, in export
    'exported_at': timezone.now().isoformat()
                   ^^^^^^^^
NameError: name 'timezone' is not defined
ERROR 2025-10-16 13:06:26,449 log 3771 6168768512 Internal Server Error: /api/v1/ai-modules/export/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/apps/api/viewsets.py", line 269, in export
    'exported_at': timezone.now().isoformat()
                   ^^^^^^^^
NameError: name 'timezone' is not defined
INFO 2025-10-16 13:08:12,649 autoreload 3771 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/api/viewsets.py changed, reloading.
INFO 2025-10-16 13:08:13,278 autoreload 3920 8765440320 Watching for file changes with StatReloader
ERROR 2025-10-16 13:09:09,551 log 3920 6199144448 Internal Server Error: /api/v1/analytics/tags/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/apps/api/analytics_views.py", line 192, in get
    'color': tag.get_color_or_default()
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tag' object has no attribute 'get_color_or_default'
ERROR 2025-10-16 13:09:22,989 log 3920 6215970816 Internal Server Error: /api/v1/analytics/tags/
Traceback (most recent call last):
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/env/lib/python3.13/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/firesieht/Documents/programming/BRICS/backend/apps/api/analytics_views.py", line 192, in get
    'color': tag.get_color_or_default()
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tag' object has no attribute 'get_color_or_default'
INFO 2025-10-16 13:10:22,787 autoreload 3920 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/tags/models.py changed, reloading.
INFO 2025-10-16 13:10:23,254 autoreload 4017 8765440320 Watching for file changes with StatReloader
INFO 2025-10-16 13:10:24,537 autoreload 4017 8765440320 /Users/firesieht/Documents/programming/BRICS/backend/apps/tags/models.py changed, reloading.
INFO 2025-10-16 13:10:24,988 autoreload 4027 8765440320 Watching for file changes with StatReloader
